version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-s3: circleci/aws-s3@1.0.15
jobs:
  build-and-test-backend:
    docker:
      - image: 'circleci/node:10'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd backend && npm install
            - run: cd backend && npm run test
  build-and-test-frontend:
    docker:
      - image: 'circleci/node:10'
    steps:
      - checkout
      - attach_workspace:
          at: ~/curapp
      - node/with-cache:
          steps:
            - run: cd frontend && npm install
            - run: cd frontend && npm run test
            - run: cd frontend && npm run build
            - run: cd frontend && ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --dir=build
      - persist_to_workspace:
          root: .
          paths:
              - frontend/build/*
      
  deploy-prod-backend:
    docker:
      - image: 'circleci/node:10'
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP "./deploy_project.sh"
  deploy-prod-frontend:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - attach_workspace:
          at: ~/curapp
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          from: ~/curapp/frontend/build
          overwrite: true
          to: 's3://tis-cdn-bucket'
      - aws-s3/copy:
          arguments: |
            --acl public-read \
            --cache-control "max-age=no-cache"
          from: ~/curapp/frontend/build/index.html
          to: 's3://tis-cdn-bucket'
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-test-backend
      - deploy-prod-backend:
          requires:
            - build-and-test-backend
          filters:
            branches:
              only: master
      - build-and-test-frontend
      - deploy-prod-frontend:
          requires:
            - build-and-test-frontend
          filters:
            branches:
              only: master