version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test-backend:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd backend
            - run: npm install
            - run: npm run test
  build-and-test-frontend:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd frontend
            - run: yarn install
            - run: yarn test
  deploy-prod-backend:
    docker:
    # specify the version you desire here (you might not want node)
    - image: circleci/node:7.10
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP "./deploy_project.sh"
  deploy-prod-frontend:
    machine:
        macos:
          xcode: '9.0'
    steps:
      - run:
          command: curl -X POST -d {} $NETLIFY_BUILD_ENDPOINT
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-test-backend
      - build-and-test-frontend
      - deploy-prod-backend:
          filters:
            branches:
              only:
                - master
          requires:
            - build-and-test-backend
      - deploy-prod-frontend:
        filters:
          branches:
            only:
              - master
        requires:
          - build-and-test-frontend